name: CI

on:
  push:
    branches: [main, mono]
    paths:
      - "apps/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/ci.yml"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      # Web
      - name: Lint web
        working-directory: apps/web
        run: pnpm run lint || echo "no lint script"

      - name: Build web
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
        run: pnpm run build

      # API
      - name: Lint api
        working-directory: apps/api
        run: pnpm run lint || echo "no lint script"

      - name: Build api
        working-directory: apps/api
        run: pnpm run build